DROP TABLE IF EXISTS `b_crm_dynamic_items_{ENTITY_TYPE_ID}`;
CREATE TABLE `b_crm_dynamic_items_{ENTITY_TYPE_ID}`
(
    `ID`                               int(11)                              NOT NULL AUTO_INCREMENT,
    `XML_ID`                           varchar(255) COLLATE utf8_unicode_ci NOT NULL,
    `TITLE`                            varchar(255) COLLATE utf8_unicode_ci NOT NULL,
    `CREATED_BY`                       int(11)                              NOT NULL,
    `UPDATED_BY`                       int(11)                              NOT NULL,
    `MOVED_BY`                         int(11)                              NOT NULL,
    `CREATED_TIME`                     datetime                             NOT NULL,
    `UPDATED_TIME`                     datetime                             NOT NULL,
    `MOVED_TIME`                       datetime                             NOT NULL,
    `CATEGORY_ID`                      int(11)                              NOT NULL,
    `OPENED`                           varchar(1) COLLATE utf8_unicode_ci   NOT NULL,
    `STAGE_ID`                         varchar(255) COLLATE utf8_unicode_ci NOT NULL,
    `PREVIOUS_STAGE_ID`                varchar(255) COLLATE utf8_unicode_ci NOT NULL,
    `BEGINDATE`                        date                                 NOT NULL,
    `CLOSEDATE`                        date                                 NOT NULL,
    `COMPANY_ID`                       int(11)                              NOT NULL,
    `CONTACT_ID`                       int(11)                              NOT NULL,
    `OPPORTUNITY`                      decimal(18, 2)                       NOT NULL,
    `IS_MANUAL_OPPORTUNITY`            varchar(1) COLLATE utf8_unicode_ci   NOT NULL,
    `TAX_VALUE`                        decimal(18, 2)                       NOT NULL,
    `CURRENCY_ID`                      varchar(255) COLLATE utf8_unicode_ci NOT NULL,
    `OPPORTUNITY_ACCOUNT`              decimal(18, 2)                       NOT NULL,
    `TAX_VALUE_ACCOUNT`                decimal(18, 2)                       NOT NULL,
    `ACCOUNT_CURRENCY_ID`              varchar(255) COLLATE utf8_unicode_ci NOT NULL,
    `MYCOMPANY_ID`                     int(11)                              NOT NULL,
    `SOURCE_ID`                        varchar(255) COLLATE utf8_unicode_ci NOT NULL,
    `SOURCE_DESCRIPTION`               text COLLATE utf8_unicode_ci         NOT NULL,
    `WEBFORM_ID`                       int(11)                              NOT NULL,
    `ASSIGNED_BY_ID`                   text COLLATE utf8_unicode_ci         NOT NULL,
    `LAST_ACTIVITY_BY`                 int(11)                              NOT NULL,
    `LAST_ACTIVITY_TIME`               datetime                             NOT NULL,
    `UF_CRM_MASTER_DEAL_NUMBER`        text COLLATE utf8_unicode_ci,
    `UF_CRM_MASTER_DEAL_END_USER`      text COLLATE utf8_unicode_ci,
    `UF_CRM_MASTER_DEAL_SUM_CURRENCY`  text COLLATE utf8_unicode_ci,
    `UF_CRM_MASTER_DEAL_COUNTRY`       text COLLATE utf8_unicode_ci,
    `UF_CRM_MASTER_DEAL_SE_REGION`     text COLLATE utf8_unicode_ci,
    `UF_CRM_MASTER_DEAL_GEO_REGION`    text COLLATE utf8_unicode_ci,
    `UF_CRM_MASTER_DEAL_CITY_OBJECT`   text COLLATE utf8_unicode_ci,
    `UF_CRM_MASTER_DEAL_INVESTMENTS_SUM`  text COLLATE utf8_unicode_ci,
    PRIMARY KEY (`ID`),
    KEY `ix_crm_type_item_{TYPE_ID}_category` (`CATEGORY_ID`),
    KEY `ix_crm_type_item_{TYPE_ID}_contact` (`CONTACT_ID`),
    KEY `ix_crm_type_item_{TYPE_ID}_company` (`COMPANY_ID`),
    KEY `ix_crm_type_item_{TYPE_ID}_last_activity_time` (`LAST_ACTIVITY_TIME`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  COLLATE = utf8_unicode_ci;

